language: R
warnings_are_errors: true
sudo: required
cache: packages

r_check_args: --as-cran

matrix:
    include:
        - os: linux
          r: release
          dist: trusty # 14.04
          env: R_DEPLOY = true
        - os: linux
          r: devel
          dist: trusty
        - os: linux
          r: oldrel
          dist: trusty
        - os: osx
          r: release
          before_install: ''
          disable_homebrew: true
        - os: osx
          r: devel
          before_install: ''
          disable_homebrew: true
    allow_failures:
        - os: osx
          r: release
          before_install: ''
          disable_homebrew: true
        - os: osx
          r: devel
          before_install: ''
          disable_homebrew: true

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev libudunits2-dev

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
      - covr

#after_success:
#    - Rscript -e "covr::codecov(function_exclusions='plot.gtfs_isochrone')"

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
    provider: script
    #script: Rscript -e 'pkgdown::deploy_site_github()'
    script: Rscript -e "covr::codecov(function_exclusions='plot.gtfs_isochrone'); pkgdown::deploy_site_github()"
    skip_cleanup: true
    on:
        branch: master
        condition: $R_DEPLOY = "true"
        #condition: $TRAVIS_OS_NAME=linux
        #R: release
